# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x02pb\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0eVerifyResponse\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x01 \x01(\x08\x32H\n\x0e\x41uthController\x12\x36\n\x0bVerifyToken\x12\x11.pb.VerifyRequest\x1a\x12.pb.VerifyResponse\"\x00\x62\x06proto3')



_VERIFYREQUEST = DESCRIPTOR.message_types_by_name['VerifyRequest']
_VERIFYRESPONSE = DESCRIPTOR.message_types_by_name['VerifyResponse']
VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:pb.VerifyRequest)
  })
_sym_db.RegisterMessage(VerifyRequest)

VerifyResponse = _reflection.GeneratedProtocolMessageType('VerifyResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYRESPONSE,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:pb.VerifyResponse)
  })
_sym_db.RegisterMessage(VerifyResponse)

_AUTHCONTROLLER = DESCRIPTOR.services_by_name['AuthController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFYREQUEST._serialized_start=18
  _VERIFYREQUEST._serialized_end=48
  _VERIFYRESPONSE._serialized_start=50
  _VERIFYRESPONSE._serialized_end=82
  _AUTHCONTROLLER._serialized_start=84
  _AUTHCONTROLLER._serialized_end=156
# @@protoc_insertion_point(module_scope)
