# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t2N\n\x0e\x41uthController\x12<\n\x0bVerifyToken\x12\x13.auth.VerifyRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_VERIFYREQUEST = DESCRIPTOR.message_types_by_name['VerifyRequest']
VerifyRequest = _reflection.GeneratedProtocolMessageType('VerifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFYREQUEST,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:auth.VerifyRequest)
  })
_sym_db.RegisterMessage(VerifyRequest)

_AUTHCONTROLLER = DESCRIPTOR.services_by_name['AuthController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFYREQUEST._serialized_start=49
  _VERIFYREQUEST._serialized_end=79
  _AUTHCONTROLLER._serialized_start=81
  _AUTHCONTROLLER._serialized_end=159
# @@protoc_insertion_point(module_scope)
