// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthControllerClient is the client API for AuthController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthControllerClient interface {
	VerifyToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type authControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthControllerClient(cc grpc.ClientConnInterface) AuthControllerClient {
	return &authControllerClient{cc}
}

func (c *authControllerClient) VerifyToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/pb.AuthController/VerifyToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthControllerServer is the server API for AuthController service.
// All implementations must embed UnimplementedAuthControllerServer
// for forward compatibility
type AuthControllerServer interface {
	VerifyToken(context.Context, *VerifyRequest) (*VerifyResponse, error)
	mustEmbedUnimplementedAuthControllerServer()
}

// UnimplementedAuthControllerServer must be embedded to have forward compatible implementations.
type UnimplementedAuthControllerServer struct {
}

func (UnimplementedAuthControllerServer) VerifyToken(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedAuthControllerServer) mustEmbedUnimplementedAuthControllerServer() {}

// UnsafeAuthControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthControllerServer will
// result in compilation errors.
type UnsafeAuthControllerServer interface {
	mustEmbedUnimplementedAuthControllerServer()
}

func RegisterAuthControllerServer(s grpc.ServiceRegistrar, srv AuthControllerServer) {
	s.RegisterService(&AuthController_ServiceDesc, srv)
}

func _AuthController_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthControllerServer).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.AuthController/VerifyToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthControllerServer).VerifyToken(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthController_ServiceDesc is the grpc.ServiceDesc for AuthController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AuthController",
	HandlerType: (*AuthControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _AuthController_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
