server:
  port: ":8080"

database:
  dbname:
  dbuser:
  dbpassword:
  dbhost:
  dbport:

microservice:
  tokenverifyendpoint: "http://localhost:8000/en/api/v1/token/verify/"
  userdetailendpoint: "http://localhost:8000/api/v1/users/"